export default {
  level: {
    primary: [
      'Primary 1',
      'Primary 2',
      'Primary 3',
      'Primary 4',
      'Primary 5',
      'Primary 6',
    ],
    secondary: [
      'Secondary 1',
      'Secondary 2',
      'Secondary 3',
      'Secondary 4',
      'Secondary 5',
    ],
    jc: ['Junior College 1', 'Junior College 2'],
  },
  subject: [
    'Math',
    'English',
    'Additional Math',
    'Science',
    'Physicals',
    'Chemistry',
    'Biology',
    'General Paper',
  ],
  stream: [
    'G1',
    'G2',
    'G3',
    'Express',
    'NA (Normal Academic)',
    'NT (Normal Technical)',
  ],
  class_size: ['Small Group', 'Big Group', '1-to-1'],
  delivery_mode: ['Onsite', 'Online', 'Hybrid'],
}
